'use client'

import Header from '@/components/Header'
import styles from './page.module.css'

export default function LicenseAgreementPage() {
  return (
    <main className={styles.main} style={{ flex: 1 }}>
      <Header showAuthButtons={true} />
      <div className={styles.container}>
        <h1 className={styles.title}>Cira Health – Terms of Service & Software License Agreement</h1>
        <div className={styles.meta}>
          <p><strong>Effective Date:</strong> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
          <p><strong>Last Updated:</strong> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        </div>
        <div className={styles.content}>
          <p className={styles.intro}>
            These Terms of Service and Software License Agreement ("Terms") govern your access to and use of the Cira Health software-as-a-service platform (the "Service"), operated by FocusKPI, Inc. ("FocusKPI," "we," "us," or "our").
          </p>
          <p className={styles.intro}>
            By creating an account, clicking "I agree," accessing, or using the Service, you agree to these Terms. If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization to these Terms.
          </p>
          <p className={styles.intro}>
            If you do not agree to these Terms, do not use the Service.
          </p>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>1) Overview of the Service</h2>
            <p>
              Cira Health provides an AI-assisted workflow that helps users generate Preliminary Hazard Analysis (PHA) draft content based on user-provided context and public data references (including FDA MAUDE references).
            </p>
            <p>The Service is designed to:</p>
            <ul>
              <li>generate draft PHA tables and narrative content, and</li>
              <li>allow users to download results for internal editing, review, and documentation workflows.</li>
            </ul>
            <p className={styles.important}>
              <strong>Important:</strong> The Service is a drafting and research assistance tool. It is not a substitute for professional, regulatory, quality, clinical, or engineering judgment.
            </p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>2) Definitions</h2>
            <p>For purposes of these Terms:</p>
            <ul>
              <li><strong>"Account"</strong> means the registered user account used to access the Service.</li>
              <li><strong>"Authorized Users"</strong> means your employees, contractors, or agents that you permit to use the Service under your Account.</li>
              <li><strong>"Customer Content"</strong> means any text, data, files, device descriptions, product information, processes, or other materials you submit into the Service.</li>
              <li><strong>"Output"</strong> means any draft reports, tables, documents, recommendations, PHA rows, summaries, or exported files generated by the Service.</li>
              <li><strong>"MAUDE"</strong> refers to the U.S. FDA Manufacturer and User Facility Device Experience database.</li>
              <li><strong>"Subscription"</strong> means a paid plan (if applicable) granting you access to paid features or usage limits.</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>3) Eligibility and Account Registration</h2>
            <ul>
              <li>You must be at least 18 years old and able to form a binding contract to use the Service.</li>
              <li>You agree to provide accurate and complete registration information and keep your Account information current. You are responsible for all activity under your Account, including use by Authorized Users.</li>
              <li>You must promptly notify us if you suspect unauthorized access to your Account.</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>4) License Grant (Your Rights)</h2>
            <p>
              Subject to your compliance with these Terms, FocusKPI grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Service during the Term for your internal business purposes.
            </p>
            <p>
              This license is granted only to you and only for the intended purpose of generating and exporting draft PHA outputs for your internal workflows.
            </p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>5) Permitted Use vs. Prohibited Use</h2>
            <h3 className={styles.subsectionTitle}>5.1 Permitted Use</h3>
            <p>You may use the Service to:</p>
            <ul>
              <li>generate PHA draft outputs for internal drafting,</li>
              <li>export/download Output for internal review and editing,</li>
              <li>share Output internally within your organization (or with your consultants) for risk management purposes.</li>
            </ul>
            <h3 className={styles.subsectionTitle}>5.2 Prohibited Use</h3>
            <p>You agree not to (and not to allow anyone else to):</p>
            <p><strong>Platform misuse</strong></p>
            <ul>
              <li>access the Service in a way that disrupts, harms, overloads, or impairs the Service;</li>
              <li>bypass rate limits, usage limits, access controls, or security features;</li>
              <li>use bots or scrapers to extract content from the Service unless we expressly allow it.</li>
            </ul>
            <p><strong>Copying / reverse engineering</strong></p>
            <ul>
              <li>reverse engineer, decompile, disassemble, or attempt to derive source code, underlying models, system prompts, or algorithms;</li>
              <li>copy, reproduce, or create derivative works of the Service.</li>
            </ul>
            <p><strong>Competing use</strong></p>
            <ul>
              <li>use the Service to develop, train, benchmark, or improve a competing product or service;</li>
              <li>resell, sublicense, rent, lease, or offer the Service as a service bureau or managed service.</li>
            </ul>
            <p><strong>Unlawful content and rights violations</strong></p>
            <ul>
              <li>upload content that you do not have the legal right to use;</li>
              <li>upload content that violates confidentiality obligations or third-party rights.</li>
            </ul>
            <p>We may suspend or terminate access if we reasonably determine you violated these Terms.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>6) Customer Content</h2>
            <h3 className={styles.subsectionTitle}>6.1 Your Responsibilities</h3>
            <p>You are solely responsible for:</p>
            <ul>
              <li>the accuracy, quality, and legality of Customer Content you submit,</li>
              <li>ensuring you have all rights, permissions, and authorizations to submit Customer Content,</li>
              <li>ensuring Customer Content does not violate applicable laws, contracts, or internal policies.</li>
            </ul>
            <h3 className={styles.subsectionTitle}>6.2 No Sensitive Personal Data (Recommended)</h3>
            <p>Unless explicitly agreed otherwise in writing, you agree not to submit:</p>
            <ul>
              <li>patient-identifiable information,</li>
              <li>protected health information (PHI),</li>
              <li>highly sensitive personal data,</li>
              <li>or other regulated personal data.</li>
            </ul>
            <p>If you need a HIPAA/BAA or similar compliance arrangement, contact us to discuss enterprise deployment options.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>7) Output, Draft Nature, and Download-Only Workflow</h2>
            <h3 className={styles.subsectionTitle}>7.1 Output is a Draft</h3>
            <p>You acknowledge that Output is generated automatically and is intended as a starting draft. It may contain:</p>
            <ul>
              <li>errors or omissions,</li>
              <li>incomplete hazard coverage,</li>
              <li>incorrect assumptions,</li>
              <li>misinterpretations of device context,</li>
              <li>formatting or classification inconsistencies.</li>
            </ul>
            <p>You are solely responsible for reviewing and validating Output before use.</p>
            <h3 className={styles.subsectionTitle}>7.2 Customer Editing Happens Outside the Service</h3>
            <p>In this version of the Service, users generally do not edit the PHA inside the platform. Instead, you may download Output and edit it using your own internal tools and processes.</p>
            <h3 className={styles.subsectionTitle}>7.3 No Guarantee of Acceptance</h3>
            <p>We do not guarantee that any Output will be accepted by regulators, auditors, notified bodies, internal quality teams, or third parties.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>8) FDA MAUDE References and Attribution</h2>
            <h3 className={styles.subsectionTitle}>8.1 Public Data Reference</h3>
            <p>The Service may provide references or supporting context drawn from MAUDE (or derived from publicly available MAUDE records).</p>
            <h3 className={styles.subsectionTitle}>8.2 No FDA Affiliation</h3>
            <p>The Service is not affiliated with, endorsed by, sponsored by, or approved by the U.S. FDA.</p>
            <h3 className={styles.subsectionTitle}>8.3 MAUDE Limitations</h3>
            <p>You acknowledge that MAUDE data may be incomplete, inaccurate, delayed, duplicated, misclassified, or otherwise imperfect. You are responsible for verifying any public database references prior to relying on them.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>9) Intellectual Property</h2>
            <h3 className={styles.subsectionTitle}>9.1 Our Ownership</h3>
            <p>FocusKPI and its licensors retain all right, title, and interest in and to the Service, including:</p>
            <ul>
              <li>all software, design, UI/UX, workflows, prompts, and systems,</li>
              <li>all underlying improvements and updates,</li>
              <li>all intellectual property rights.</li>
            </ul>
            <p>No rights are granted except as expressly stated in these Terms.</p>
            <h3 className={styles.subsectionTitle}>9.2 Your Ownership (Customer Content)</h3>
            <p>You retain ownership of your Customer Content.</p>
            <h3 className={styles.subsectionTitle}>9.3 Output Ownership</h3>
            <p>As between you and FocusKPI, you own the Output generated specifically for you through your use of the Service.</p>
            <p>However:</p>
            <ul>
              <li>FocusKPI retains ownership of the Service mechanics and templates used to generate the Output.</li>
              <li>The Service may generate similar outputs for others if inputs overlap or are similar.</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>10) Feedback</h2>
            <p>If you provide suggestions, feature requests, or feedback ("Feedback"), you grant FocusKPI the right to use that Feedback without restriction or obligation, including to improve the Service.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>11) Pay-Per-Download Fees, Billing, and Refunds</h2>
            <h3 className={styles.subsectionTitle}>11.1 Pay-Per-Download Pricing</h3>
            <p>The Service is offered on a pay-per-download basis. Fees apply when you choose to download or export a report or other Output (each, a "Report Download").</p>
            <p>The applicable fee (the "Download Fee") will be displayed in the Service before you complete the download.</p>
            <p>FocusKPI may update Download Fees from time to time. Any updated pricing will apply only to future Report Downloads.</p>
            <h3 className={styles.subsectionTitle}>11.2 Free Preview vs. Paid Download</h3>
            <p>You may be able to preview portions of Output in the Service before purchasing.</p>
            <p>You acknowledge that the paid feature is the ability to download/export the Output. Preview availability and preview limits may vary and may change over time.</p>
            <h3 className={styles.subsectionTitle}>11.3 When You Are Charged</h3>
            <p>You will be charged at the time you confirm a Report Download (e.g., clicking "Download," "Export," or a similar purchase button), and the download will be made available after successful payment.</p>
            <h3 className={styles.subsectionTitle}>11.4 Payment Method and Authorization</h3>
            <p>By providing a payment method, you authorize FocusKPI (and our payment processors) to charge the Download Fee and any applicable taxes to your selected payment method.</p>
            <h3 className={styles.subsectionTitle}>11.5 Taxes</h3>
            <p>Download Fees exclude taxes unless stated otherwise. You are responsible for all applicable taxes, duties, or governmental charges.</p>
            <h3 className={styles.subsectionTitle}>11.6 No Refunds</h3>
            <p>All Report Downloads are final and non-refundable, except as required by law.</p>
            <p>However, FocusKPI may, at its sole discretion, issue a refund or credit in limited cases such as:</p>
            <ul>
              <li>duplicate charges, or</li>
              <li>a confirmed technical issue where a paid Report Download was not successfully delivered.</li>
            </ul>
            <p>To request billing support, contact cirahealth@focuskpi.com.</p>
            <h3 className={styles.subsectionTitle}>11.7 Chargebacks and Payment Disputes</h3>
            <p>If you believe you were charged in error, you agree to contact us first to resolve the issue. If you initiate a chargeback without contacting us, we may suspend or terminate your access to the Service.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>12) Availability, Support, and Changes</h2>
            <h3 className={styles.subsectionTitle}>12.1 Availability</h3>
            <p>We aim to keep the Service available, but we do not guarantee uninterrupted availability. The Service may be temporarily unavailable due to maintenance, upgrades, outages, or circumstances beyond our control.</p>
            <h3 className={styles.subsectionTitle}>12.2 Support</h3>
            <p>Support level depends on your plan. We may provide support via email or in-product channels on a reasonable-efforts basis.</p>
            <h3 className={styles.subsectionTitle}>12.3 Changes</h3>
            <p>We may modify, update, or discontinue features of the Service at any time. If changes materially reduce core functionality of a paid plan, we may provide notice where reasonable.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>13) Security</h2>
            <p>We take reasonable measures designed to protect the Service and user data. However, no system is perfectly secure, and you acknowledge that:</p>
            <ul>
              <li>internet-based services carry inherent risks,</li>
              <li>you are responsible for maintaining appropriate security controls for your accounts and internal environments.</li>
            </ul>
            <p>If you require enhanced security terms (e.g., SOC 2, custom retention, private deployment), contact us.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>14) Confidentiality (Optional Website Section)</h2>
            <p>If you provide non-public information to us, we will treat it as confidential and use it only to provide and improve the Service, unless:</p>
            <ul>
              <li>you authorize otherwise,</li>
              <li>the information becomes public through no fault of ours,</li>
              <li>disclosure is required by law.</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>15) Compliance Disclaimer (High-Importance)</h2>
            <p>The Service is not a regulated medical device and does not provide clinical decision-making functionality.</p>
            <p>Output is provided for drafting support only and does not constitute:</p>
            <ul>
              <li>medical advice,</li>
              <li>legal advice,</li>
              <li>regulatory advice,</li>
              <li>or a guarantee of compliance with any standard (including ISO 14971 or FDA guidance).</li>
            </ul>
            <p>You are solely responsible for ensuring your final risk documentation meets your organization's and regulator's requirements.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>16) Warranty Disclaimer</h2>
            <p className={styles.legal}>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE AND OUTPUT ARE PROVIDED "AS IS" AND "AS AVAILABLE."
            </p>
            <p className={styles.legal}>
              FOCUSKPI DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AVAILABILITY, AND NON-INFRINGEMENT.
            </p>
            <p>We do not warrant that:</p>
            <ul>
              <li>the Output is complete or accurate,</li>
              <li>the Output is free from errors,</li>
              <li>the Output is suitable for any specific regulatory submission or audit.</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>17) Limitation of Liability</h2>
            <p className={styles.legal}>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW:
            </p>
            <p className={styles.legal}>
              FOCUSKPI WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR LOSS OF PROFITS, REVENUE, DATA, OR BUSINESS INTERRUPTION.
            </p>
            <p className={styles.legal}>
              FOCUSKPI'S TOTAL LIABILITY ARISING OUT OF OR RELATED TO THESE TERMS WILL NOT EXCEED THE TOTAL AMOUNT YOU PAID TO FOCUSKPI FOR THE SERVICE IN THE [3 / 6 / 12] MONTHS IMMEDIATELY BEFORE THE EVENT GIVING RISE TO THE CLAIM.
            </p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>18) Indemnification (Customer)</h2>
            <p>You agree to defend, indemnify, and hold harmless FocusKPI and its officers, directors, employees, and agents from any claims, damages, liabilities, losses, and expenses (including reasonable attorneys' fees) arising out of or related to:</p>
            <ul>
              <li>your Customer Content,</li>
              <li>your use of the Output,</li>
              <li>your violation of these Terms,</li>
              <li>your violation of laws or third-party rights.</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>19) Suspension and Termination</h2>
            <h3 className={styles.subsectionTitle}>19.1 Suspension</h3>
            <p>We may suspend access to the Service if we reasonably believe:</p>
            <ul>
              <li>your account is compromised,</li>
              <li>your use threatens the security, integrity, or availability of the Service,</li>
              <li>you violated these Terms.</li>
            </ul>
            <h3 className={styles.subsectionTitle}>19.2 Termination</h3>
            <p>You may stop using the Service at any time.</p>
            <p>We may terminate your Account if you materially breach these Terms.</p>
            <p>Upon termination:</p>
            <ul>
              <li>your right to access the Service ends,</li>
              <li>certain sections will survive (including ownership, disclaimers, limitation of liability, and indemnification).</li>
            </ul>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>20) Governing Law and Dispute Resolution</h2>
            <p>These Terms are governed by the laws of the State of [Delaware / California / New York], without regard to conflict-of-law principles.</p>
            <p>Any disputes will be brought exclusively in the state or federal courts located in [County, State], unless otherwise required by applicable law.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>21) Changes to These Terms</h2>
            <p>We may update these Terms from time to time. If we make material changes, we will update the "Last Updated" date and may provide additional notice.</p>
            <p>Your continued use of the Service after updated Terms become effective means you accept them.</p>
          </section>

          <section className={styles.section}>
            <h2 className={styles.sectionTitle}>22) Contact</h2>
            <p>For questions about these Terms, contact:</p>
            <p>
              <strong>FocusKPI, Inc.</strong><br />
              Email: cirahealth@focuskpi.com<br />
              Address: [Company Address]
            </p>
          </section>
        </div>
      </div>
    </main>
  )
}
